# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-28 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mooc.save


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mooc', '0003_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='视频名称')),
                ('intro', models.TextField(blank=True, max_length=500, null=True, verbose_name='视频描述')),
                ('photo', models.ImageField(blank=True, null=True, storage=mooc.save.newStorage(), unique=True, upload_to='photos/%Y/%m/%d/', verbose_name='展示图片')),
                ('video', models.FileField(blank=True, null=True, storage=mooc.save.newStorage(), unique=True, upload_to='videos/%Y/%m/%d', verbose_name='视频')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '视频信息管理',
                'verbose_name_plural': '视频信息管理',
                'ordering': ('-created_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='secondtag',
            options={'verbose_name': '二级标签', 'verbose_name_plural': '二级标签管理'},
        ),
        migrations.AlterField(
            model_name='secondtag',
            name='uptag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suptag', to='mooc.Maintag', verbose_name='一级标签'),
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supSecondtag', to='mooc.Secondtag', verbose_name='标签'),
        ),
    ]
