# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc', '0004_auto_20190128_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(unique=True, upload_to='jslide/', verbose_name='滚动图片')),
                ('intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片介绍')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '滚动图片管理',
                'verbose_name_plural': '滚动图片信息管理',
                'ordering': ('-created_time',),
            },
        ),
    ]
